### ISSUE TITLE
Error generating ns_output

### ISSUE THREAD

**Issue by martindevora** [MNGuenther/allesfitter#49] opened 2022-01-19 21:49 UTC
Hi, the generation of the ns_output crashes when creating an image. Hence, no single_transits_plot, no corner_plot, neither ns_table or ns_derived_table files are generated. It happened after fitting many TESS sectors together (thus many transits). This is the stack:

```
Image size of 600x129200 pixels is too large. It must be less than 2^16 in each direction.
Traceback (most recent call last):
  File "/home/mdevora/.local/lib/python3.8/site-packages/sherlockpipe/fit.py", line 94, in fit
    allesfitter.ns_output(allesfit_dir)
  File "/usr/local/lib/python3.8/site-packages/allesfitter/nested_sampling_output.py", line 133, in ns_output
    fig.savefig( os.path.join(config.BASEMENT.outdir,'ns_fit_per_transit_'+inst+'_'+companion+'.pdf'), bbox_inches='tight' )
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    self.figure.draw(renderer)
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/artist.py", line 37, in draw_wrapper
    renderer.start_rasterizing()
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/backends/backend_mixed.py", line 88, in start_rasterizing
    self._raster_renderer = self._raster_renderer_class(
  File "/usr/local/lib64/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 96, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 600x129200 pixels is too large. It must be less than 2^16 in each direction.
Generating custom plots
```

Regards.

**Comment by MNGuenther** [comment] 2022-04-29 12:12
Hi Martin, thanks for your patience with me getting to this since it is a very case-specific issue. Could you send me an email (maximilian.guenther at esa dot int) with a Dropbox link (or the like) that contains all your files (data, params.csv, settings.csv, results, etc.)? Then I can run it and try to reproduce your issue. I will close this issue for now and we can discuss all the details applying to your case via email!

**Closed by MNGuenther** 2022-04-29 12:12 UTC
